server {
    listen 8086;

    location /videos/ {
        alias /videos/;
        add_header Accept-Ranges bytes;
        add_header Cache-Control "public, max-age=86400";
        add_header Access-Control-Allow-Origin *;
    }

    location /videos.json {
        alias /videos/videos.json;
        add_header Cache-Control "no-cache";
        add_header Access-Control-Allow-Origin "*";
    }

    location /health {
        return 200 '{"status":"ok"}';
        add_header Content-Type application/json;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
